app:
  name: 'go-mall-api'
  version: '1.0.0'

http:
  port: '8080'
  version: '1'

logger:
  log_level: 'debug'
  rollbar_env: 'go-clean-template'

datasource:
  pg:
    username: 'postgres'
    password: 'postgres'
    host: 'localhost'
    port: '5432'
    database: 'postgres'
    sslmode: 'disable'

prometheus:
  gateway: 'http://localhost:9091/'
